config/routes.rb
Autogiftr::Application.routes.draw do
  resources :gifts

  resources :occasions

  resources :recipients

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  has_many :occasions
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipient }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:name, :user_id)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= simple_form_for(@recipient) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.name %></td>
        <td><%= recipient.user %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipient.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipient.user %>
</p>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>