config/routes.rb
Autogiftr::Application.routes.draw do
  resources :gifts

  resources :occasions

  resources :recipients

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  belongs_to :recipient
  has_many :gift_occasions
  has_many :gifts, through: :gift_occasions
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:show, :edit, :update, :destroy]

  # GET /occasions
  # GET /occasions.json
  def index
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
  end

  # GET /occasions/new
  def new
    @occasion = Occasion.new
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = Occasion.new(occasion_params)

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @occasion }
      else
        format.html { render action: 'new' }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:title, :date, :recipient_id)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= simple_form_for(@occasion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :recipient, collection: current_user.recipients,as: :radio_buttons %>
    <%= f.input :title, label: 'Title for occasion', placeholder: 'eg. Birthday, anniversary, St Valentines Day etc' %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<h1>Editing occasion</h1>

<%= render 'form' %>

<%= link_to 'Show', @occasion %> |
<%= link_to 'Back', occasions_path %>

app/views/occasions/index.html.erb
<h1>Listing occasions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Recipient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.title %></td>
        <td><%= occasion.date %></td>
        <td><%= occasion.recipient %></td>
        <td><%= link_to 'Show', occasion %></td>
        <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
        <td><%= link_to 'Destroy', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occasion', new_occasion_path %>

app/views/occasions/new.html.erb
<h1>New occasion</h1>

<%= render 'form' %>

<%= link_to 'Back', occasions_path %>

app/views/occasions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @occasion.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @occasion.date %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @occasion.recipient %>
</p>

<%= link_to 'Edit', edit_occasion_path(@occasion) %> |
<%= link_to 'Back', occasions_path %>